---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

params:
  NSX_API_MANAGER:
  NSX_API_USER:
  NSX_API_PASSWORD:
  PAS_SYSTEM_DOMAIN:
  PAS_APPS_DOMAIN:
  NSX_T_OVERLAY_TRANSPORT_ZONE:
  NSX_T_T0ROUTER_NAME:
  NSX_T_CONTAINER_IP_BLOCK_SPEC:
  NSX_T_EXTERNAL_IP_POOL_SPEC:

inputs:
  - name: nsx-t-ci-pipeline

run:
  path: nsx-t-ci-pipeline/tasks/validate-nsx-t-for-pas/task.sh
