---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  PIVNET_API_TOKEN:
  IAAS:

inputs:
  - name: pivnet-product
  - name: nsx-t-ci-pipeline

run:
  path: nsx-t-ci-pipeline/tasks/upload-product-and-stemcell/task.sh
